services:
  wordpress:
    build: ./requirements/wordpress/
    image: wordpress:1337
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/
    networks:
      - inception-net
    restart: always

  nginx:
    build: ./requirements/nginx/
    image: nginx:1337
    container_name: nginx
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/
    ports:
      - 443:443
    networks:
      - inception-net
    restart: always

  mariadb:
    build: ./requirements/mariadb/
    image: mariadb:1337
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql/
    networks:
      - inception-net
    restart: always

networks:
  inception-net:

volumes:
  db:
    driver_opts:
      type: none
      o: bind
      device: /home/aait-lfd/data/db/

  wordpress:
    driver_opts:
      type: none
      o: bind
      device: /home/aait-lfd/data/wordpress/
